public enum TypeInteractionsBoard
{
    SPECIFIC_PICK_DECK,
    RANDOM_PICK_DECK,
    ADD_HAND,
    REMOVE_HAND,
    ADD_GROUND,
    REMOVE_GROUND,
    BUFF_CARD_GROUND,
    DEBUFF_CARD_GROUND,
    BUFF_RELIC_GROUND,
    DEBUFF_RELIC_GROUND,
    WAITING_SOMETHING
}